name: SAST Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        # Executa o Semgrep CLI diretamente, usando o conjunto de regras "p/default"
        # que é um conjunto abrangente de regras da comunidade.
        # A flag --no-verify impede o semgrep de verificar a conexao com o dashboard, o que pode causar problemas em algumas redes
        # Usamos `continue-on-error: true` para garantir que os passos seguintes executem mesmo se o semgrep encontrar problemas e falhar.
        id: semgrep
        continue-on-error: true
        run: semgrep ci --config "p/default" --sarif --output=semgrep.sarif --no-verify

      - name: Verify SARIF file creation
        run: ls -la
        
      - name: Upload SARIF file
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif
          if-no-files-found: warn # Alterado para 'warn' para podermos depurar

#      - name: Upload to DefectDojo
#        # Este passo sempre será executado para garantir que os resultados sejam registrados.
#        if: always()
#        # Usa uma Action para fazer o upload do relatório SARIF para o DefectDojo.
#        uses: defectdojo/defectdojo-action@v1.1.0
#        with:
#          # URL da sua instância do DefectDojo (a partir dos Secrets)
#          defectdojo_url: ${{ secrets.DOJO_URL }}
#          # Chave de API do DefectDojo (a partir dos Secrets)
#          defectdojo_api_key: ${{ secrets.DOJO_API_KEY }}
#          # Nome do produto no DefectDojo.
#          product_name: 'poc-sast-free'
#          # Nome do "Engagement" para agrupar os scans. Usamos o SHA do commit para unicidade.
#          engagement_name: 'GitHub Actions SAST - ${{ github.sha }}'
#          # Tipo de scan. Importante para o DefectDojo saber como processar o arquivo.
#          scan_type: 'Semgrep Scan'
#          # Caminho para o arquivo de relatório gerado pelo Semgrep.
#          file_path: 'semgrep.sarif' 