name: SAST Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        # Voltamos à instalação manual, que se provou mais robusta neste ambiente.
        # O 'semgrep ci' é o comando ideal para produção, pois foca em novas vulnerabilidades
        # Usamos múltiplos conjuntos de regras para máxima cobertura de detecção.
        # Por padrão, 'semgrep ci' bloqueia apenas em severidade 'ERROR', que é o ideal.
        run: semgrep ci --config="p/security-audit" --config="p/owasp-top-ten" --config="p/cwe-top-25" --config="auto" --sarif --output="semgrep.sarif"

      - name: Show custom error on failure
        if: failure()
        run: |
          echo "::error::Bloqueio de PR: Foram encontradas vulnerabilidades que violam a política de segurança. Por favor, verifique os logs do passo 'Run Semgrep Scan' acima para ver os detalhes das vulnerabilidades."

      - name: Upload SARIF file
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif
          if-no-files-found: error

#      - name: Upload to DefectDojo
#        # Este passo sempre será executado para garantir que os resultados sejam registrados.
#        if: always()
#        # Usa uma Action para fazer o upload do relatório SARIF para o DefectDojo.
#        uses: defectdojo/defectdojo-action@v1.1.0
#        with:
#          # URL da sua instância do DefectDojo (a partir dos Secrets)
#          defectdojo_url: ${{ secrets.DOJO_URL }}
#          # Chave de API do DefectDojo (a partir dos Secrets)
#          defectdojo_api_key: ${{ secrets.DOJO_API_KEY }}
#          # Nome do produto no DefectDojo.
#          product_name: 'poc-sast-free'
#          # Nome do "Engagement" para agrupar os scans. Usamos o SHA do commit para unicidade.
#          engagement_name: 'GitHub Actions SAST - ${{ github.sha }}'
#          # Tipo de scan. Importante para o DefectDojo saber como processar o arquivo.
#          scan_type: 'Semgrep Scan'
#          # Caminho para o arquivo de relatório gerado pelo Semgrep.
#          file_path: 'semgrep.sarif' 